Controllers/CargosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers
{
    public class CargosController : Controller
    {
        private readonly GestaoTarefasIPGDbContext _context;
        private const int NUMERO_DE_CARGOS_POR_PAGINA = 5;
        private const int NUMERO_DE_PAGINAS_ANTES_DEPOIS = 3;

        public CargosController(GestaoTarefasIPGDbContext context)
        {
            _context = context;
        }

        // GET: Cargos
        public IActionResult Index(int page = 1)
        {
            decimal numberProducts = _context.Cargos.Count();
            CargosViewModel vm = new CargosViewModel
            {
                Cargos = _context.Cargos
                //.OrderBy(p => p.Nome)
                .Skip((page - 1) * NUMERO_DE_CARGOS_POR_PAGINA)
                .Take(NUMERO_DE_CARGOS_POR_PAGINA),
                PaginaAtual = page,
                TotalPaginas = (int)Math.Ceiling(numberProducts / NUMERO_DE_CARGOS_POR_PAGINA),
                PrimeiraPagina = Math.Max(1, page - NUMERO_DE_PAGINAS_ANTES_DEPOIS),
            };
            vm.UltimaPagina = Math.Min(vm.TotalPaginas, page + NUMERO_DE_PAGINAS_ANTES_DEPOIS);
            return View(vm);
        }
        // GET: Cargos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargos = await _context.Cargos
                .FirstOrDefaultAsync(m => m.CargosId == id);
            if (cargos == null)
            {
                return NotFound();
            }

            return View(cargos);
        }

        // GET: Cargos/Create
        [Authorize(Roles = "admin,func")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cargos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CargosId,Nome,Superior")] Cargos cargos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cargos);
                await _context.SaveChangesAsync();
                ViewBag.Message = "Setor criado com sucesso!";
                return View("ViewSUCESSSO");
            }
            return View(cargos);
        }

        // GET: Cargos/Edit/5
        [Authorize(Roles = "admin,func")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargos = await _context.Cargos.FindAsync(id);
            if (cargos == null)
            {
                return NotFound();
            }
            return View(cargos);
        }

        // POST: Cargos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CargosId,Nome,Superior")] Cargos cargos)
        {
            if (id != cargos.CargosId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cargos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CargosExists(cargos.CargosId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.Message = "Setor editado com sucesso!";
                return View("ViewSUCESSSO");
            }
            return View(cargos);
        }

        // GET: Cargos/Delete/5
        [Authorize(Roles = "admin,func")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cargos = await _context.Cargos
                .FirstOrDefaultAsync(m => m.CargosId == id);
            if (cargos == null)
            {
                return NotFound();
            }

            return View(cargos);
        }

        // POST: Cargos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cargos = await _context.Cargos.FindAsync(id);
            _context.Cargos.Remove(cargos);
            await _context.SaveChangesAsync();
            ViewBag.Message = "Setor apagado com sucesso!";
            return View("ViewSUCESSSO");
        }

        private bool CargosExists(int id)
        {
            return _context.Cargos.Any(e => e.CargosId == id);
        }
    }
}

Controllers/ColaboradoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers
{
    public class ColaboradoresController : Controller
    {
        private readonly GestaoTarefasIPGDbContext _context;
        private const int NUMERO_DE_COLABORADORES_POR_PAGINA = 5;
        private const int NUMERO_DE_PAGINAS_ANTES_DEPOIS = 3;

        public ColaboradoresController(GestaoTarefasIPGDbContext context)
        {
            _context = context;
        }

        // GET: Colaboradores
        public IActionResult Index(int page = 1)
        {
            decimal numberProducts = _context.Colaboradores.Count();
            ColaboradoresViewModel vm = new ColaboradoresViewModel
            {
                Colaboradores = _context.Colaboradores
                //.OrderBy(p => p.Nome)
                .Skip((page - 1) * NUMERO_DE_COLABORADORES_POR_PAGINA)
                .Take(NUMERO_DE_COLABORADORES_POR_PAGINA),
                PaginaAtual = page,
                TotalPaginas = (int)Math.Ceiling(numberProducts / NUMERO_DE_COLABORADORES_POR_PAGINA),
                PrimeiraPagina = Math.Max(1, page - NUMERO_DE_PAGINAS_ANTES_DEPOIS),
            };
            vm.UltimaPagina = Math.Min(vm.TotalPaginas, page + NUMERO_DE_PAGINAS_ANTES_DEPOIS);
            return View(vm);
        }
        

        // GET: Colaboradores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaboradores = await _context.Colaboradores
                .FirstOrDefaultAsync(m => m.ColaboradoresId == id);
            if (colaboradores == null)
            {
                return NotFound();
            }

            return View(colaboradores);
        }

        // GET: Colaboradores/Create
        [Authorize(Roles = "admin,func")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Colaboradores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nome,ColaboradoresId,Profissao,DataNascimento,email")] Colaboradores colaboradores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(colaboradores);
                await _context.SaveChangesAsync();
                ViewBag.Message = "Colaborador criado com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            return View(colaboradores);
        }

        // GET: Colaboradores/Edit/5
        [Authorize(Roles = "admin,func")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaboradores = await _context.Colaboradores.FindAsync(id);
            if (colaboradores == null)
            {
                return NotFound();
            }
            return View(colaboradores);
        }

        // POST: Colaboradores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nome,ColaboradoresId,Profissao,DataNascimento,email")] Colaboradores colaboradores)
        {

            if (id != colaboradores.ColaboradoresId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(colaboradores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ColaboradoresExists(colaboradores.ColaboradoresId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.Message = "Colaborador editado com sucesso!";
                return RedirectToAction(nameof(Index));
            }
            return View(colaboradores);
        }

        // GET: Colaboradores/Delete/5
        [Authorize(Roles = "admin,func")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var colaboradores = await _context.Colaboradores
                .FirstOrDefaultAsync(m => m.ColaboradoresId == id);
            if (colaboradores == null)
            {
                return NotFound();
            }

            return View(colaboradores);
        }

        // POST: Colaboradores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            var colaboradores = await _context.Colaboradores.FindAsync(id);
            _context.Colaboradores.Remove(colaboradores);
            await _context.SaveChangesAsync();
            ViewBag.Message = "Colaborador apagado com sucesso!";
            return View("ViewSUCESSSO");
        }
        
       
        private bool ColaboradoresExists(int id)
        {
            return _context.Colaboradores.Any(e => e.ColaboradoresId == id);
        }
    }
}

Controllers/SetorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers
{
    public class SetorsController : Controller
    {
    
        private readonly GestaoTarefasIPGDbContext _context;
        private const int NUMERO_DE_SETORES_POR_PAGINA = 5;
        private const int NUMERO_DE_PAGINAS_ANTES_DEPOIS = 3;
        public SetorsController(GestaoTarefasIPGDbContext context)
        {
            _context = context;
        }


        public IActionResult Index(int page = 1)
        {
            decimal numberProducts = _context.Setor.Count();
            SetoresViewModel vm = new SetoresViewModel
            {
                Setores = _context.Setor
                //.OrderBy(p => p.Nome)
                .Skip((page - 1) * NUMERO_DE_SETORES_POR_PAGINA)
                .Take(NUMERO_DE_SETORES_POR_PAGINA),
                PaginaAtual = page,
                TotalPaginas = (int)Math.Ceiling(numberProducts / NUMERO_DE_SETORES_POR_PAGINA),
                PrimeiraPagina = Math.Max(1, page - NUMERO_DE_PAGINAS_ANTES_DEPOIS),
            };
            vm.UltimaPagina = Math.Min(vm.TotalPaginas, page + NUMERO_DE_PAGINAS_ANTES_DEPOIS);
            return View(vm);
        }

        // GET: Setors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var setor = await _context.Setor
                .FirstOrDefaultAsync(m => m.SetorId == id);
            if (setor == null)
            {
                return NotFound();
            }

            return View(setor);
        }

        [Authorize(Roles = "admin,func")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Setors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SetorId,Nome,Local")] Setor setor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(setor);
                await _context.SaveChangesAsync();
                ViewBag.Message = "Setor criado com sucesso!";
                
                return View("ViewSUCESSSO");
            }

            return View(setor);
        }

        [Authorize(Roles = "admin,func")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var setor = await _context.Setor.FindAsync(id);
            if (setor == null)
            {
                return NotFound();
            }
            return View(setor);
        }

        // POST: Setors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SetorId,Nome,Local")] Setor setor)
        {
            if (id != setor.SetorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(setor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SetorExists(setor.SetorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewBag.Message = "Setor editado com sucesso!";
                return View("ViewSUCESSSO");
            }
            return View(setor);
        }

        [Authorize(Roles = "admin,func")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var setor = await _context.Setor
                .FirstOrDefaultAsync(m => m.SetorId == id);
            if (setor == null)
            {
                return NotFound();
            }

            return View(setor);
        }

        // POST: Setors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var setor = await _context.Setor.FindAsync(id);
            _context.Setor.Remove(setor);
            await _context.SaveChangesAsync();
            ViewBag.Message = "Setor apagado com sucesso!";
            return View("ViewSUCESSSO");
        }

        private bool SetorExists(int id)
        {
            return _context.Setor.Any(e => e.SetorId == id);
        }
    }
}

Views/Shared/ViewSUCESSSO.cshtml
@{
    ViewData["Title"] = "ViewSUCESSSO";
}
<div style="position: relative;">
    <h1 style="font-size:70px;">SUCESSSO</h1>
    <h4 style="color:white;">@ViewBag.Message</h4>
    <hr>
    <a asp-action="Index" class="btn btn-primary">Voltar</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestaoTarefasIPG</title>
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="~/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/jquery-ui.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/css/aos.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body>
    <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">

        <div class="container-fluid">
            <div class="d-flex align-items-center">
                <div class="site-logo mr-auto w-25"><a href="index.html">GestãoTarefasIPG</a></div>

                <div class="mx-auto text-center">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav mx-auto d-none d-lg-block  m-0 p-0">
                            <li><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a class="nav-link" asp-controller="Setors" asp-action="Index">Setor</a></li>
                            <li><a class="nav-link" asp-controller="Cargos" asp-action="Index">Cargos</a></li>
                            <li><a class="nav-link" asp-controller="Colaboradores" asp-action="Index">Colaboradores</a></li>
                        </ul>
                    </nav>
                </div>
     
                <div class="ml-auto w-25">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu site-menu-dark js-clone-nav mr-auto d-none d-lg-block m-0 p-0">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="cta"><a asp-area="Identity" asp-page="/account/login" class="nav-link"><span>LOGIN</span></a></li>
                            }
                            else
                            {
                                @if (User.IsInRole("admin"))
                                 {
                                    <li class="cta"><a asp-area="Identity" asp-page="/account/register" class="nav-link"><span>Registar</span></a></li>
                                 }
                                <li class="cta"><a asp-area="Identity" asp-page="/account/logout" class="nav-link" asp-route-returnUrl="@Url.Action("Index","Home", new { area = "" })" method="post"><span>LOGOUT</span></a></li>
                            }
                        </ul>
                    </nav>
                    <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right"><span class="icon-menu h3"></span></a>
                </div>
            </div>
        </div>
    </header>
    <div class="intro-section" id="home-section">
        <div class="slide-1" style="background-image: url('/images/IPG.jpg');" data-stellar-background-ratio="0.5">
            <div class="container">
                <div class="row align-items-center">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>

    <script src="js/jquery-3.3.1.min.js"></script>
    <script src="js/jquery-migrate-3.0.1.min.js"></script>
    <script src="js/jquery-ui.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.stellar.min.js"></script>
    <script src="js/jquery.countdown.min.js"></script>
    <script src="js/bootstrap-datepicker.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/aos.js"></script>
    <script src="js/jquery.fancybox.min.js"></script>
    <script src="js/jquery.sticky.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>